# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'

- task: SynopsysDetectTask@8
  inputs:
    Products: BD
    BlackDuckService: 'ec2-18-220-53-153.us-east-2.compute.amazonaws.com'
    DetectFolder: .
    DetectArguments: |
      --blackduck.url="https://ec2-18-220-53-153.us-east-2.compute.amazonaws.com/"
      --blackduck.api.token="ZDg1NmE2YmUtZWVhMy00YzlkLWIyOTktZjMzY2M2OTBhNDY0OjdmYTUyZGY5LWExNDctNDYxNi04NDZlLTljNWU0ZWYzMDhkNQ=="
      --detect.project.name="ado-test"
      --detect.project.version.name="test1"
      --detect.detector.search.depth="10"
    DetectVersion: 'latest'